// @ts-check
import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import react from "@astrojs/react";
import { rehypeAutoLinks } from "./src/lib/rehype-auto-links.ts";
import { rehypeLazyImages } from "./src/lib/rehype-lazy-images.ts";
import { rehypeDemoteSkillHeadings } from "./src/lib/rehype-demote-skill-headings.ts";

import cloudflare from "@astrojs/cloudflare";

// https://astro.build/config
export default defineConfig({
	// Placeholder until the final production domain is set up (matches the
	// fallback already hardcoded in AppLayout.astro) — required so
	// rss.xml.js and canonical/OG URLs have a `site` to build against;
	// swap this for the real domain once it's live.
	site: "https://doodleai.art",
	// No @astrojs/sitemap: the sitemap is generated by src/pages/sitemap.xml.ts so
	// we control exactly which URLs are listed (it must exclude the noindex
	// /admin and /bid routes) and what lastmod reports.
	// react() is here ONLY for the tldraw canvas island on /c/[id]. Every
	// other surface in this app is plain Astro + vanilla TS and should stay
	// that way — tldraw is React-only, so the canvas is rendered with
	// client:only="react" and never touches the SSR/Worker bundle.
	markdown: {
		// rehypeDemoteSkillHeadings only touches src/mastra/skills/*/SKILL.md, so
		// that /skills/[id] can embed a skill file without ending up with two <h1>s.
		rehypePlugins: [rehypeAutoLinks, rehypeLazyImages, rehypeDemoteSkillHeadings],
	},
	integrations: [mdx(), react()],
	build: {
		/* The 2026-08-28 audit found four render-blocking stylesheets on the
		   homepage (the `_id_.*.css` chunks — Astro names shared CSS bundles after
		   one of the pages importing them, so these are shared app styles, not the
		   chat route's CSS leaking in) totalling 15.9 KiB. On Slow 4G that is four
		   serial round trips ahead of first paint. Astro's default 'auto' only
		   inlines chunks under 4 kB, which leaves all four as separate requests;
		   'always' folds them into the HTML. Worth it at this total size — revisit
		   if shared CSS grows past ~30 KiB, where the added HTML weight on every
		   navigation starts to outweigh the saved round trips. */
		inlineStylesheets: 'always',
	},
	// `astro dev`'s own dev server (via the adapter's local bindings) is NOT how
	// this project develops against the database — see package.json's `dev`
	// script. Wrangler's mixed-mode "remote bindings" (one binding proxied to
	// the real Cloudflare resource while `astro dev` serves everything else
	// locally) turned out to be broken for this account: Cloudflare's preview
	// session exchange returns an HTML challenge page instead of JSON. `pnpm
	// dev` instead builds the Worker and runs it under `wrangler dev
	// --remote --env staging`, Wrangler's older and fully reliable full-remote
	// mode, which needs no per-binding config here at all. `configPath` below
	// keeps `astro dev` available as a manual escape hatch for UI-only iteration
	// (ephemeral local-emulated D1/KV, no shared data) if anyone ever wants fast
	// Vite HMR and doesn't need real data.
	adapter: cloudflare({
		// astro 7 / @astrojs/cloudflare 14 dropped the v12 `platformProxy` option:
		// the adapter now builds through `@cloudflare/vite-plugin`, which reads the
		// wrangler config directly. Unlike v12's `platformProxy.configPath` (which
		// scoped a config to DEV-ONLY binding emulation), v14's `configPath` is the
		// config the WHOLE adapter uses — including the deploy config it emits into
		// dist/server/wrangler.json and the redirect at .wrangler/deploy/config.json.
		// It must therefore stay on the real deploy config (wrangler.json, the
		// default), which is where the Durable Object bindings, cron trigger and
		// Secrets Store bindings live. Pointing it at wrangler.local.json — the
		// minimal DB+KV-only escape-hatch config — silently stripped all three from
		// the built config and produced a binding-less deploy. `configPath` is left
		// unset so it defaults to wrangler.json; `pnpm dev:local` still passes
		// wrangler.local.json explicitly to its own migration step, and `astro dev`
		// simply sees the full bindings (harmless — the real dev path is `pnpm dev`).
		//
		// Run the build-time prerender pass in Node, not in a workerd worker.
		//
		// astro 7 / @astrojs/cloudflare 14 default `prerenderEnvironment` to
		// "workerd", which boots the REAL deployed Worker (via miniflare) to
		// render static routes. That worker imports this project's entry
		// (src-worker/entry.ts), whose re-exported Durable Objects — RoadmapRoom,
		// BoardRoom (extends `DurableObject` from cloudflare:workers) and
		// VoiceRoom (extends `Agent` from `agents`) — are instantiated by
		// miniflare's DO wrapper at startup. In that prerender worker the
		// `cloudflare:workers` base class resolves to `undefined`, so the wrapper
		// dies with `Class extends value undefined is not a constructor` before a
		// single page renders. The DO classes are only needed by the DEPLOYED
		// worker (for binding resolution); prerendering never touches them. Running
		// the pass in Node skips the workerd boot entirely and the failure with it.
		prerenderEnvironment: "node",
	}),
	vite: {
		resolve: {
			/* One React instance, always.
			 *
			 * `@cloudflare/voice/react` (the voice hook) declares React as a peer. In
			 * dev, Vite pre-bundles the island's React but left this package's import
			 * unoptimized, so the two resolved DIFFERENT React instances at runtime —
			 * producing "Invalid hook call / mismatching versions of React" and
			 * `Cannot read properties of null (reading 'useMemo')`, which killed the
			 * voice surface on mount (it rendered nothing at all). Deduping forces a
			 * single copy for every importer. */
			dedupe: ["react", "react-dom"],
		},
		optimizeDeps: {
			/* Pre-bundle the voice hook alongside React so it links against the SAME
			 * optimized React instance as the canvas island (see resolve.dedupe). */
			include: ["@cloudflare/voice/react", "react", "react-dom", "react-dom/client"],
		},
		server: {
			/* Dev-only: do NOT raise Vite's full-screen error overlay.
			 *
			 * Adding the voice packages (`agents` brings a `vite` peer + `yaml`)
			 * makes pnpm resolve a second vite closure, and Vite's dependency
			 * pre-scanner can then run on the instance lacking Astro's `.astro`
			 * plugin — parsing `.astro` markup as raw JS and throwing a bogus
			 * `Expected ";"` on a valid `href={...}` in SkillCard.astro.
			 *
			 * The scan failure itself is harmless (every route still serves, and the
			 * production build is unaffected — it never runs this pass). The OVERLAY
			 * is not: it covers the page and intercepts pointer events, so clicking
			 * anything — the Talk button included — silently did nothing in local
			 * dev. Turning the overlay off restores a usable dev surface while
			 * leaving dependency optimization intact.
			 *
			 * NOT `optimizeDeps.noDiscovery` — that skips pre-bundling entirely and
			 * tldraw's CommonJS deps (lodash.isequalwith) then fail to import, which
			 * stops the whole canvas island from hydrating. Verified.
			 *
			 * Real errors still surface in the terminal and the browser console. */
			hmr: { overlay: false },
			/* Vite rejects any request whose Host header it doesn't recognise, so a
			   tunnelled webhook delivery to `astro dev` comes back 403 "This host is
			   not allowed" before it ever reaches /api/webhooks/picx. PicX only sees
			   a non-2xx and retries, which reads as a broken receiver.

			   Dev-server-only setting (the build ignores it), scoped to the two
			   tunnel providers we actually use rather than `true`, which would
			   disable the DNS-rebinding check for every host. Set DEV_ALLOWED_HOST
			   for a different tunnel domain. */
			allowedHosts: [
				".ngrok-free.app",
				".ngrok.app",
				".trycloudflare.com",
				...(process.env.DEV_ALLOWED_HOST ? [process.env.DEV_ALLOWED_HOST] : []),
			],
		},
		build: {
			rollupOptions: {
				external: [
					"@ast-grep/napi",
					"execa",
					"cross-spawn",
					"human-signals",
					"which",
					"isexe",
					"yoctocolors",
					"is-unicode-supported",
					"npm-run-path",
					"unicorn-magic",
					"path-key",
					"signal-exit",
					"get-stream",
					"strip-final-newline",
					"mimic-fn",
				],
			},
		},
		ssr: {
			// @mastra/core's optional workspace-skills feature statically pulls
			// in a chunk of Node-only CLI process-spawning tooling (execa and
			// its dependency chain) plus a native ast-grep binary — none of
			// which is installed, needed, or runnable on Cloudflare Workers.
			// /api/agent only ever calls agent.generate(), which never
			// exercises that code path, so it's safe to leave these external
			// rather than have Rollup fail trying to bundle them. See
			// README.md's Cloudflare/Mastra note.
			external: [
				"@ast-grep/napi",
				"execa",
				"cross-spawn",
				"human-signals",
				"which",
				"isexe",
				"yoctocolors",
				"is-unicode-supported",
				"npm-run-path",
				"unicorn-magic",
				"path-key",
				"signal-exit",
				"get-stream",
				"strip-final-newline",
				"mimic-fn",
			],
		},
	},
});
