// @ts-check
import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";

import cloudflare from "@astrojs/cloudflare";

// https://astro.build/config
export default defineConfig({
	// The new worker's public site URL will be set after local validation and domain setup.
	// No @astrojs/sitemap: the sitemap is generated by src/pages/sitemap.xml.ts so
	// we control exactly which URLs are listed (it must exclude the noindex
	// /admin and /bid routes) and what lastmod reports.
	integrations: [mdx()],
	adapter: cloudflare({
		platformProxy: {
			enabled: true,
		},
	}),
});
