// @ts-check
import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";

import cloudflare from "@astrojs/cloudflare";

// https://astro.build/config
export default defineConfig({
	// Placeholder until the final production domain is set up (matches the
	// fallback already hardcoded in AppLayout.astro) — required so
	// rss.xml.js and canonical/OG URLs have a `site` to build against;
	// swap this for the real domain once it's live.
	site: "https://doodlebooth.lol",
	// No @astrojs/sitemap: the sitemap is generated by src/pages/sitemap.xml.ts so
	// we control exactly which URLs are listed (it must exclude the noindex
	// /admin and /bid routes) and what lastmod reports.
	integrations: [mdx()],
	adapter: cloudflare({
		platformProxy: {
			enabled: true,
		},
	}),
});
