interface ProjectDto{id:string;name:string;brief:string|null;assetCount:number;}
interface AssetDto{id:string;url:string;kind:string;name:string|null;reviewState:string;reviewNote:string|null;}
const stateLabels:Record<string,string>={draft:"Draft",in_review:"In review",changes_requested:"Changes requested",approved:"Approved"};
function initProjectDetail():void{const root=document.getElementById("projectDetail");if(!root)return;const id=root.getAttribute("data-project-id");if(!id)return;const projectId=id;const grid=document.getElementById("assetGrid");let assets:AssetDto[]=[];let filter="all";const error=document.getElementById("assetError");
  async function request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(path,{credentials:"include",...init});const body=await response.json().catch(()=>null) as T&{error?:{message?:string}};if(!response.ok)throw new Error(body?.error?.message||"Request failed.");return body;}
  function render():void{if(!grid)return;const visible=filter==="all"?assets:assets.filter(asset=>asset.reviewState===filter);grid.innerHTML="";if(!visible.length){grid.innerHTML='<div class="team-loading">No assets in this view yet.</div>';return;}visible.forEach(asset=>{const card=document.createElement("article");card.className="asset-card";const image=document.createElement("img");image.src=asset.url;image.alt=asset.name||"Project asset";image.loading="lazy";const state=document.createElement("span");state.className="asset-state";state.textContent=stateLabels[asset.reviewState]||asset.reviewState;const body=document.createElement("div");body.className="asset-card-body";const title=document.createElement("strong");title.textContent=asset.name||"Untitled asset";const kind=document.createElement("small");kind.textContent=asset.kind;body.appendChild(title);body.appendChild(kind);const controls=document.createElement("div");controls.className="asset-card-controls";if(asset.reviewState==="draft"||asset.reviewState==="changes_requested"){const submit=document.createElement("button");submit.textContent="Submit review";submit.addEventListener("click",()=>void transition(asset,"in_review"));controls.appendChild(submit);}if(asset.reviewState==="in_review"){const approve=document.createElement("button");approve.textContent="Approve";approve.addEventListener("click",()=>void transition(asset,"approved"));const changes=document.createElement("button");changes.textContent="Request changes";changes.addEventListener("click",()=>void transition(asset,"changes_requested"));controls.appendChild(approve);controls.appendChild(changes);}card.appendChild(image);card.appendChild(state);card.appendChild(body);card.appendChild(controls);grid.appendChild(card);});}
  async function transition(asset:AssetDto,next:string):Promise<void>{try{const payload=await request<{asset:AssetDto}>(`/api/v1/assets/${encodeURIComponent(asset.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({reviewState:next})});assets=assets.map(item=>item.id===asset.id?payload.asset:item);render();}catch(error){window.dispatchEvent(new CustomEvent("doodleai:toast",{detail:{text:error instanceof Error?error.message:"Couldn't update review state."}}));}}
  async function load():Promise<void>{try{const project=await request<{project:ProjectDto}>(`/api/v1/projects/${encodeURIComponent(projectId)}`);const name=document.getElementById("detailProjectName");const brief=document.getElementById("detailProjectBrief");if(name)name.textContent=project.project.name;if(brief)brief.textContent=project.project.brief||"Build, review, and share a focused set of visual directions.";const payload=await request<{assets:AssetDto[]}>(`/api/v1/projects/${encodeURIComponent(projectId)}/assets`);assets=payload.assets;render();}catch(err){const name=document.getElementById("detailProjectName");if(name)name.textContent=err instanceof Error?err.message:"Project unavailable.";}}
  document.querySelectorAll<HTMLButtonElement>("#reviewFilters button").forEach(button=>button.addEventListener("click",()=>{filter=button.dataset.state||"all";document.querySelectorAll("#reviewFilters button").forEach(item=>item.setAttribute("data-active",String(item===button)));render();}));
  document.getElementById("addAssetButton")?.addEventListener("click",()=>{const panel=document.getElementById("assetAddPanel");if(panel)panel.hidden=!panel.hidden;});
  document.getElementById("saveAssetButton")?.addEventListener("click",async()=>{const url=document.getElementById("assetUrlInput") as HTMLInputElement|null;const name=document.getElementById("assetNameInput") as HTMLInputElement|null;if(!url?.value.trim()){if(error){error.textContent="Add an image URL.";error.hidden=false;}return;}try{const payload=await request<{asset:AssetDto}>(`/api/v1/projects/${encodeURIComponent(projectId)}/assets`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:url.value.trim(),name:name?.value.trim()||undefined,kind:"upload"})});assets=[payload.asset,...assets];render();if(url)url.value="";if(name)name.value="";}catch(err){if(error){error.textContent=err instanceof Error?err.message:"Couldn't add asset.";error.hidden=false;}}});
  document.getElementById("shareProjectButton")?.addEventListener("click",async()=>{try{const payload=await request<{link:{url:string}}>(`/api/v1/projects/${encodeURIComponent(projectId)}/share`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});try{await navigator.clipboard.writeText(payload.link.url);}catch (clipboardError) { void clipboardError; }window.dispatchEvent(new CustomEvent("doodleai:toast",{detail:{text:"Review link copied"}}));}catch(err){window.dispatchEvent(new CustomEvent("doodleai:toast",{detail:{text:err instanceof Error?err.message:"Couldn't create a review link."}}));}});
  document.getElementById("runBatchButton")?.addEventListener("click",async()=>{const skill=(document.getElementById("batchSkill") as HTMLSelectElement|null)?.value||"normal";const variantCount=Number((document.getElementById("batchCount") as HTMLSelectElement|null)?.value||3);const status=document.getElementById("batchStatus");const button=document.getElementById("runBatchButton") as HTMLButtonElement|null;if(button){button.disabled=true;button.textContent="Starting…";}try{const payload=await request<{batch:{id:string}}>("/api/v1/batches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({skillId:skill,variantCount,projectId})});if(status)status.textContent=`Batch started — ${variantCount} variants are running.`;const poll=async():Promise<void>=>{const current=await request<{batch:{status:string;items:{status:string}[]}}>(`/api/v1/batches/${encodeURIComponent(payload.batch.id)}`);const done=current.batch.items.filter(item=>["ok","failed","canceled"].includes(item.status)).length;if(status)status.textContent=`Batch ${current.batch.status} · ${done}/${current.batch.items.length} complete`;if(["done","failed","canceled"].includes(current.batch.status)){if(button){button.disabled=false;button.textContent="Run batch";}await load();return;}window.setTimeout(()=>void poll(),2000);};await poll();}catch(err){if(status)status.textContent=err instanceof Error?err.message:"Couldn't start the batch.";if(button){button.disabled=false;button.textContent="Run batch";}}});
  void load();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initProjectDetail);else initProjectDetail();
