import { setBackgroundImageUrl } from "./dom-utils";

interface OrgDto{id:string;name:string;isPersonal:boolean;balance:number;memberCount:number;}
interface MemberDto{id:string;userId:string;name:string;email:string;image:string|null;role:string;spend30d:number;}
interface LinkDto{id:string;url:string;role:string;uses:number;maxUses:number|null;revokedAt:number|null;}
interface LedgerEntry{delta:number;reason:string;actorName:string;createdAt:number;}
async function initTeamSettings():Promise<void>{const root=document.getElementById("teamSettings");if(!root)return;async function request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(path,{credentials:"include",...init});const body=await response.json().catch(()=>null) as T&{error?:{message?:string}};if(!response.ok)throw new Error(body?.error?.message||"Request failed.");return body;}
  try{const me=await request<{org:OrgDto}>("/api/v1/me");const org=me.org;const nameInput=document.getElementById("renameTeamInput") as HTMLInputElement|null;if(nameInput)nameInput.value=org.name;const memberPayload=await request<{members:MemberDto[]}>(`/api/v1/orgs/${encodeURIComponent(org.id)}/members`);const memberRoot=document.getElementById("settingsMembers");const count=document.getElementById("memberCountLabel");if(count)count.textContent=`${memberPayload.members.length} member${memberPayload.members.length===1?"":"s"}`;if(memberRoot){memberRoot.innerHTML="";memberPayload.members.forEach(member=>{const row=document.createElement("div");row.className="member-row";const identity=document.createElement("div");identity.className="member-identity";const avatar=document.createElement("span");avatar.className="member-avatar";avatar.textContent=member.name.charAt(0).toUpperCase();if(member.image)setBackgroundImageUrl(avatar,member.image);const text=document.createElement("div");const strong=document.createElement("strong");strong.textContent=member.name;const small=document.createElement("small");small.textContent=member.email;text.appendChild(strong);text.appendChild(small);identity.appendChild(avatar);identity.appendChild(text);const role=document.createElement("span");role.className="member-role";role.textContent=member.role;const spend=document.createElement("span");spend.className="member-spend";spend.textContent=`${member.spend30d} credits / 30d`;row.appendChild(identity);row.appendChild(role);row.appendChild(spend);memberRoot.appendChild(row);});}
    const credits=await request<{balance:number;monthSpend:number;monthlyCreditCap:number|null}>(`/api/v1/orgs/${encodeURIComponent(org.id)}/credits`);const summary=document.getElementById("creditSummary");if(summary)summary.textContent=`${credits.balance} credits available · ${credits.monthSpend} used this month${credits.monthlyCreditCap?` · ${credits.monthlyCreditCap} monthly cap`:""}`;
    await renderLinks(org.id);await renderLedger(org.id);
    document.getElementById("renameTeamForm")?.addEventListener("submit",async(event)=>{event.preventDefault();const input=document.getElementById("renameTeamInput") as HTMLInputElement|null;if(!input?.value.trim())return;const status=document.getElementById("renameStatus");try{await request(`/api/v1/orgs/${encodeURIComponent(org.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:input.value.trim()})});if(status)status.textContent="Saved";setTimeout(()=>{if(status)status.textContent="";},1800);}catch(error){if(status)status.textContent=error instanceof Error?error.message:"Couldn't save.";}});
    document.getElementById("createLinkButton")?.addEventListener("click",async()=>{try{const payload=await request<{link:LinkDto}>(`/api/v1/orgs/${encodeURIComponent(org.id)}/invite-links`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({role:"artist",expiresInDays:14})});try{await navigator.clipboard.writeText(payload.link.url);}catch (clipboardError) { void clipboardError; }window.dispatchEvent(new CustomEvent("doodleai:toast",{detail:{text:"Invite link copied"}}));await renderLinks(org.id);}catch(error){window.dispatchEvent(new CustomEvent("doodleai:toast",{detail:{text:error instanceof Error?error.message:"Couldn't create link."}}));}});
    document.getElementById("settingsInviteButton")?.addEventListener("click",()=>window.dispatchEvent(new Event("doodleai:open-team-invite")));
  }catch(error){const heading=document.querySelector(".settings-heading p");if(heading)heading.textContent=error instanceof Error?error.message:"Couldn't load team settings.";}
  async function renderLinks(orgId:string):Promise<void>{const target=document.getElementById("inviteLinks");if(!target)return;const payload=await request<{links:LinkDto[]}>(`/api/v1/orgs/${encodeURIComponent(orgId)}/invite-links`);target.innerHTML="";const active=payload.links.filter(link=>!link.revokedAt);if(!active.length){const empty=document.createElement("div");empty.className="team-loading";empty.textContent="No reusable links yet.";target.appendChild(empty);return;}active.forEach(link=>{const row=document.createElement("div");row.className="invite-link-row";const url=document.createElement("span");url.className="invite-link-url";url.textContent=link.url;const actions=document.createElement("div");actions.className="invite-link-actions";const uses=document.createElement("small");uses.textContent=`${link.role} · ${link.uses}${link.maxUses?`/${link.maxUses}`:""} uses`;const copy=document.createElement("button");copy.className="mini-button";copy.textContent="Copy";copy.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(link.url);}catch (clipboardError) { void clipboardError; }window.dispatchEvent(new CustomEvent("doodleai:toast",{detail:{text:"Invite link copied"}}));});const revoke=document.createElement("button");revoke.className="mini-button";revoke.textContent="Revoke";revoke.addEventListener("click",async()=>{await request(`/api/v1/orgs/${encodeURIComponent(orgId)}/invite-links?linkId=${encodeURIComponent(link.id)}`,{method:"DELETE"});await renderLinks(orgId);});actions.appendChild(uses);actions.appendChild(copy);actions.appendChild(revoke);row.appendChild(url);row.appendChild(actions);target.appendChild(row);});}
  async function renderLedger(orgId:string):Promise<void>{const target=document.getElementById("ledgerList");if(!target)return;const payload=await request<{entries:LedgerEntry[]}>(`/api/v1/orgs/${encodeURIComponent(orgId)}/credits/ledger?limit=8`);target.innerHTML="";if(!payload.entries.length){const empty=document.createElement("div");empty.className="team-loading";empty.textContent="No credit activity yet.";target.appendChild(empty);return;}payload.entries.forEach(entry=>{const row=document.createElement("div");row.className="ledger-row";const left=document.createElement("span");left.textContent=entry.reason.replaceAll("_"," ");const small=document.createElement("small");small.textContent=`${entry.actorName} · ${new Date(entry.createdAt).toLocaleDateString()}`;left.appendChild(small);const amount=document.createElement("strong");amount.className=entry.delta>=0?"ledger-positive":"ledger-negative";amount.textContent=`${entry.delta>=0?"+":""}${entry.delta}`;row.appendChild(left);row.appendChild(amount);target.appendChild(row);});}
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>void initTeamSettings());else void initTeamSettings();
